included:
  - mobile

excluded:
  - "**/.build"
  - "**/Android"
  - "**/Skip"
  - "**/Darwin"
  - "**/Tests"
  - "**/Package.swift"

disabled_rules:
  - multiple_closures_with_trailing_closure
  - contrasted_opening_brace
  - explicit_self
  - indentation_width
  - missing_docs
  - extension_access_modifier
  - one_declaration_per_file
  - prefixed_toplevel_constant
  - required_deinit
  - explicit_acl
  - explicit_type_interface
  - no_magic_numbers
  - object_literal
  - prefer_asset_symbols
  - expiring_todo
  - file_name
  - file_types_order
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - function_default_parameter_at_end
  - nimble_operator
  - prefer_nimble
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - balanced_xctest_lifecycle
  - empty_xctest_method
  - final_test_case
  - single_test_class
  - test_case_accessibility
  - xct_specific_matcher
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - redundant_self
  - explicit_enum_raw_value

opt_in_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - array_init
  - async_without_await
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - direct_return
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - explicit_top_level_acl
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - incompatible_concurrency_annotation
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_call_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_empty_block
  - no_extension_access_modifier
  - no_grouping_extension
  - non_overridable_class_declaration
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  - prefer_condition_list
  - prefer_key_path
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - private_swiftui_state
  - prohibited_interface_builder
  - prohibited_super_call
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - required_enum_case
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - self_binding
  - shorthand_argument
  - shorthand_optional_binding
  - sorted_enum_cases
  - sorted_first_last
  - sorted_imports
  - static_operator
  - static_over_final_class
  - strict_fileprivate
  - strong_iboutlet
  - superfluous_else
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unhandled_throwing_task
  - unneeded_escaping
  - unneeded_parentheses_in_closure_argument
  - unneeded_throws_rethrows
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_parameter
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

analyzer_rules:
  - capture_variable
  - typesafe_array_init
  - unused_declaration
  - unused_import

file_header:
  forbidden_pattern: ".*"

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 10

cyclomatic_complexity:
  warning: 15
  error: 25

closure_body_length:
  warning: 110
  error: 200

trailing_comma:
  mandatory_comma: true

vertical_whitespace:
  max_empty_lines: 1

force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: error

implicitly_unwrapped_optional:
  severity: error
  mode: all

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 60
    error: 80
  allowed_symbols:
    - _

reporter: xcode
