name: MovieDesktop
options:
  bundleIdPrefix: dev.lazyconvex.desktop
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
packages:
  shared:
    path: ../shared
  swift-cross-ui:
    url: https://github.com/stackotter/swift-cross-ui.git
    branch: main
targets:
  Movie:
    type: application
    platform: macOS
    sources:
      - path: Sources
    dependencies:
      - package: shared
        product: DesktopShared
      - package: swift-cross-ui
        product: SwiftCrossUI
      - package: swift-cross-ui
        product: DefaultBackend
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.lazyconvex.desktop.movie
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: true
  MovieUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: UITests
    dependencies:
      - target: Movie
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.lazyconvex.desktop.movie.uitests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: minimal
        GENERATE_INFOPLIST_FILE: true
schemes:
  Movie:
    build:
      targets:
        Movie: all
    run:
      config: Debug
    test:
      targets:
        - MovieUITests
  MovieUITests:
    build:
      targets:
        Movie: all
    test:
      targets:
        - MovieUITests
